### Матрицы и операции над ними

In [1]:
import numpy as np

### Создание матриц
Самый простой способ — с помощью функции __`numpy.array(list, dtype=None, ...)`__.

В качестве первого аргумента ей надо передать итерируемый объект, элементами которого являются другие итерируемые объекты одинаковой длины и содержащие данные одинакового типа.

Второй аргумент является опциональным и определяет тип данных матрицы. Его можно не задавать, тогда тип данных будет определен из типа элементов первого аргумента. При задании этого параметра будет произведена попытка приведения типов.


In [3]:
matrix = np.array([
    [1,3,4],
    [2,5,6],
    [0,5,19]
])
print('Matrix:')
matrix

Matrix:


array([[ 1,  3,  4],
       [ 2,  5,  6],
       [ 0,  5, 19]])

Альтернативные способы определения матрицы:
- __`numpy.eye(N, M=None, ...)`__ создает еденичную матрицу
- __`numpy.zeros(shape, ...)`__ создает матрицу целиеом из нулей
- __`numpy.ones(shape, ...)`__ создае матрицу целиком из едениц
-  __`numpy.arange([start, ]stop, [step, ], ...).reshape(shape)`__

In [7]:
ones = np.ones((3,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [12]:
diagonal = np.eye(3)
diagonal

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [14]:
m = np.arange(0,20,2).reshape(2,5)
m

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

### Индексирование
- Обращение к элементу матрицы:  __`array[i, j]`__
- Срез матрицы: __`array[i, :]`__
- Выбор каждого элемента __`array[[i0,i1...], [j0,j1...]]`__ 

In [19]:
# Простое индексирование
print(m[1,4])

# Поэлементное обращение
print(m[[0,1],[0,2]]) 

18
[ 0 14]


### Умножение матриц и столбцов
Операция умножения определена для двух матриц, таких что число столбцов первой равно числу строк второй. 

Пусть матрицы $A$ и $B$ таковы, что $A \in \mathbb{R}^{n \times k}$ и $B \in \mathbb{R}^{k \times m}$. Произведением матриц $A$ и $B$ называется матрица $C$, такая что $c_{ij} = \sum_{r=1}^{k} a_{ir}b_{rj}$, где $c_{ij}$ — элемент матрицы $C$, стоящий на пересечении строки с номером $i$ и столбца с номером $j$.

В `NumPy` произведение матриц вычисляется:
- При помощи функции: __`numpy.dot(a, b, ...)`__ 
- При помощи метода: __`a.dot(b)`__

In [52]:
# Определяем матрицы 
a = np.array([
    [1,0,2],
    [10,4,3]
])

b = np.array([
    [0,1,10],
    [100,200,500],
    [1,9,10] 
])

print(a.shape, b.shape)

(2, 3) (3, 3)


Видно, что основное правило выполянется, итоговая матрица будет иметь размерность 2x3

In [22]:
res_m = a.dot(b)
res_m.shape

(2, 3)

Однако можно осуществлять и обычное умножение (поэлементное) ```*```. Но в этом случае размерности должны совпадать!

### Транспонирование матриц
Транспонированной матрицей $A^{T}$ называется матрица, полученная из исходной матрицы $A$ заменой строк на столбцы. Формально: элементы матрицы $A^{T}$ определяются как $a^{T}_{ij} = a_{ji}$, где $a^{T}_{ij}$ — элемент матрицы $A^{T}$, стоящий на пересечении строки с номером $i$ и столбца с номером $j$.

- __`numpy.transpose()`__
- __`array.T`__

### Определитель матрицы
Для **квадратных матриц** существует понятие __определителя__.

Пусть $A$ — квадратная матрица. __Определителем__ (или __детерминантом__) матрицы $A \in \mathbb{R}^{n \times n}$ назовем число 

$$\det A = \sum_{\alpha_{1}, \alpha_{2}, \dots, \alpha_{n}} (-1)^{N(\alpha_{1}, \alpha_{2}, \dots, \alpha_{n})} \cdot a_{\alpha_{1} 1} \cdot \cdot \cdot a_{\alpha_{n} n},
$$
где $\alpha_{1}, \alpha_{2}, \dots, \alpha_{n}$ — перестановка чисел от $1$ до $n$, $N(\alpha_{1}, \alpha_{2}, \dots, \alpha_{n})$ — число инверсий в перестановке, суммирование ведется по всем возможным перестановкам длины $n$.

Например, для матрицы размера $2 \times 2$ получается:

$$\det \left( \begin{array}{cc} a_{11} & a_{12} \\ a_{21} & a_{22}  \end{array} \right) = a_{11} a_{22} - a_{12} a_{21}
$$


Вычисление определителя матрицы по определению требует порядка $n!$ операций, поэтому разработаны методы, которые позволяют вычислять его быстро и эффективно.

- __`numpy.linalg.det(a)`__

### Ранг матрицы
__Рангом матрицы__ $A$ называется максимальное число линейно независимых строк (столбцов) этой матрицы. Векторы линейно независимы тогда и только тогда, когда ранг полученной матрицы совпадает с числом векторов.

- __`numpy.linalg.matrix_rank(M, tol=None)`__

### Системы линейных уравнений
__Системой линейных алгебраических уравнений__ называется система вида $Ax = b$, где $A \in \mathbb{R}^{n \times m}, x \in \mathbb{R}^{m \times 1}, b \in \mathbb{R}^{n \times 1}$. В случае квадратной невырожденной матрицы $A$ решение системы единственно.

- __`numpy.linalg.solve(a, b)`__

In [44]:
a = np.array([[3, 1], [1, 2]])
b = np.array([9, 8])
x = np.linalg.solve(a, b)

# Убедимся, что вектор x действительно является решением системы:
print(a.dot(x))

[9. 8.]


Бывают случаи, когда решение системы не существует. Но хотелось бы все равно "решить" такую систему. Логичным кажется искать такой вектор $x$, который минимизирует выражение $\left\Vert Ax - b\right\Vert^{2}$ — так мы приблизим выражение $Ax$ к $b$.

В `NumPy` такое псевдорешение можно искать с помощью функции __`numpy.linalg.lstsq(a, b, ...)`__

### Обращение матриц
Для квадратных невырожденных матриц определено понятие __обратной__ матрицы. 

Пусть $A$ — квадратная невырожденная матрица. Матрица $A^{-1}$ называется __обратной матрицей__ к $A$, если 

$$AA^{-1} = A^{-1}A = I,
$$ 

где $I$ — единичная матрица.

- __`numpy.linalg.inv(a)`__ 

### Собственные числа и собственные вектора матрицы
Для квадратных матриц определены понятия __собственного вектора__ и __собственного числа__.

Пусть $A$ — квадратная матрица и $A \in \mathbb{R}^{n \times n}$. __Собственным вектором__ матрицы $A$ называется такой ненулевой вектор $x \in \mathbb{R}^{n}$, что для некоторого $\lambda \in \mathbb{R}$ выполняется равенство $Ax = \lambda x$. При этом $\lambda$ называется __собственным числом__ матрицы $A$. Собственные числа и собственные векторы матрицы играют важную роль в теории линейной алгебры и ее практических приложениях.

- __`numpy.linalg.eig(a)`__

В качестве результата эта функция выдает одномерный массив __`w`__ собственных чисел и двумерный массив __`v`__, в котором по столбцам записаны собственные вектора, так что вектор __`v[:, i]`__ соотвествует собственному числу __`w[i]`__.

In [54]:
np.linalg.eig(b)

(array([221.89436778,  -3.48227444,  -8.41209334]),
 array([[-0.00641624, -0.84806723, -0.40209243],
        [-0.99907735, -0.40951582, -0.81378073],
        [-0.04246509,  0.33627187,  0.41962198]]))

__Обратите внимание:__ у вещественной матрицы собственные значения или собственные векторы могут быть комплексными.